# Generated by Django 5.1.5 on 2025-01-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('production_year', models.IntegerField()),
                ('car_body', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
            ],
        ),
    ]
